In [1]:
%pylab inline
from sklearn import cross_validation, metrics, neighbors, datasets

Populating the interactive namespace from numpy and matplotlib


In [2]:
# load train and test data
mnist_train = np.loadtxt('../data/train.csv', delimiter=',', dtype=int, skiprows=1)
mnist_test = np.loadtxt('../data/test.csv', delimiter=',', dtype=int, skiprows=1)

In [3]:
# split the data into training and validation sets
X_train, X_test, y_train, y_test = cross_validation.train_test_split(mnist_train[:,1:], mnist_train[:,0])

In [ ]:
# train nn on train data
knn = neighbors.KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=1, p=2, weights='uniform')

In [ ]:
# predict test data
Z = knn.predict(X_test)

In [14]:
# accuracy
matches = (Z == y_test)
matches.sum() / float(len(matches))

0.96657142857142853

In [19]:
#f1 score
print metrics.classification_report(Z, y_test)

             precision    recall  f1-score   support

          0       0.99      0.98      0.99       994
          1       1.00      0.97      0.98      1174
          2       0.97      0.99      0.98      1031
          3       0.95      0.96      0.96      1084
          4       0.96      0.97      0.97      1013
          5       0.95      0.95      0.95       968
          6       0.98      0.98      0.98      1026
          7       0.98      0.96      0.97      1130
          8       0.93      0.98      0.95       966
          9       0.96      0.94      0.95      1114

avg / total       0.97      0.97      0.97     10500



In [16]:
# confusion matrix
print metrics.confusion_matrix(Z, y_test)

[[ 972    0    5    2    0    2    7    0    2    4]
 [   0 1134    8    1   10    2    2    5   10    2]
 [   0    0 1016    9    0    0    0    3    3    0]
 [   0    0    3 1043    0   20    1    0   12    5]
 [   0    2    2    0  985    1    4    3    2   14]
 [   1    0    0   19    0  922    8    0   18    0]
 [   2    1    0    1    2   10 1005    0    5    0]
 [   0    2   14    8    1    0    0 1081    4   20]
 [   1    0    4   11    0    2    0    0  946    2]
 [   1    0    0    6   25    7    0   12   18 1045]]


In [17]:
Z_test = knn.predict(mnist_test)